src/Entity/Live.php
<?php

namespace App\Entity;

use App\Repository\LiveRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LiveRepository::class)
 */
class Live
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $artist;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="datetime", length=255)
     */
    private $date_created;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $date_live;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $schedule;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $facebook;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $instagram;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $twitter;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $youtube;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $deezer;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $spotify;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $soundcloud;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="lives")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $live_type;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ticket;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $live_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $genre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $subgenre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $postcode;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $latitude;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $longitude;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getArtist(): ?string
    {
        return $this->artist;
    }

    public function setArtist(string $artist): self
    {
        $this->artist = $artist;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getDateCreated(): ?\DateTimeInterface
    {
        return $this->date_created;
    }

    public function setDateCreated(\DateTimeInterface $date_created): self
    {
        $this->date_created = $date_created;

        return $this;
    }

    public function getDateLive(): ?string
    {
        return $this->date_live;
    }

    public function setDateLive(string $date_live): self
    {
        $this->date_live = $date_live;

        return $this;
    }

    public function getSchedule(): ?string
    {
        return $this->schedule;
    }

    public function setSchedule(string $schedule): self
    {
        $this->schedule = $schedule;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getFacebook(): ?string
    {
        return $this->facebook;
    }

    public function setFacebook(?string $facebook): self
    {
        $this->facebook = $facebook;

        return $this;
    }

    public function getInstagram(): ?string
    {
        return $this->instagram;
    }

    public function setInstagram(?string $instagram): self
    {
        $this->instagram = $instagram;

        return $this;
    }

    public function getTwitter(): ?string
    {
        return $this->twitter;
    }

    public function setTwitter(?string $twitter): self
    {
        $this->twitter = $twitter;

        return $this;
    }

    public function getYoutube(): ?string
    {
        return $this->youtube;
    }

    public function setYoutube(?string $youtube): self
    {
        $this->youtube = $youtube;

        return $this;
    }

    public function getDeezer(): ?string
    {
        return $this->deezer;
    }

    public function setDeezer(?string $deezer): self
    {
        $this->deezer = $deezer;

        return $this;
    }

    public function getSpotify(): ?string
    {
        return $this->spotify;
    }

    public function setSpotify(?string $spotify): self
    {
        $this->spotify = $spotify;

        return $this;
    }

    public function getSoundcloud(): ?string
    {
        return $this->soundcloud;
    }

    public function setSoundcloud(?string $soundcloud): self
    {
        $this->soundcloud = $soundcloud;

        return $this;
    }

    public function getUser(): ?Users
    {
        return $this->user;
    }

    public function setUser(?Users $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getLiveType(): ?string
    {
        return $this->live_type;
    }

    public function setLiveType(string $live_type): self
    {
        $this->live_type = $live_type;

        return $this;
    }

    public function getTicket(): ?string
    {
        return $this->ticket;
    }

    public function setTicket(?string $ticket): self
    {
        $this->ticket = $ticket;

        return $this;
    }

    public function getLiveName(): ?string
    {
        return $this->live_name;
    }

    public function setLiveName(string $live_name): self
    {
        $this->live_name = $live_name;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(?string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(string $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    public function getSubgenre(): ?string
    {
        return $this->subgenre;
    }

    public function setSubgenre(string $subgenre): self
    {
        $this->subgenre = $subgenre;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostcode(): ?string
    {
        return $this->postcode;
    }

    public function setPostcode(string $postcode): self
    {
        $this->postcode = $postcode;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getLatitude(): ?string
    {
        return $this->latitude;
    }

    public function setLatitude(string $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?string
    {
        return $this->longitude;
    }

    public function setLongitude(string $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }
}

src/Entity/Release.php
<?php

namespace App\Entity;

use App\Repository\ReleaseRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\EntityManagerInterface;

/**
 * @ORM\Entity(repositoryClass=ReleaseRepository::class)
 * @ORM\Table(name="`release`")
 */
class Release
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $artist;

    /**
     * @ORM\Column(type="datetime", length=255)
     */
    private $date_created;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $release_type;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $date_release;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $release_name;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $facebook;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $instagram;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $twitter;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $youtube;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $deezer;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $spotify;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $soundcloud;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="releases")
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $genre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $subgenre;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getArtist(): ?string
    {
        return $this->artist;
    }

    public function setArtist(string $artist): self
    {
        $this->artist = $artist;

        return $this;
    }

    public function getDateCreated(): ?\DateTimeInterface
    {
        return $this->date_created;
    }

    public function setDateCreated(\DateTimeInterface $date_created): self
    {
        $this->date_created = $date_created;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getReleaseType(): ?string
    {
        return $this->release_type;
    }

    public function setReleaseType(string $release_type): self
    {
        $this->release_type = $release_type;

        return $this;
    }

    public function getDateRelease(): ?string
    {
        return $this->date_release;
    }

    public function setDateRelease(string $date_release): self
    {
        $this->date_release = $date_release;

        return $this;
    }

    public function getReleaseName(): ?string
    {
        return $this->release_name;
    }

    public function setReleaseName(string $release_name): self
    {
        $this->release_name = $release_name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getFacebook(): ?string
    {
        return $this->facebook;
    }

    public function setFacebook(?string $facebook): self
    {
        $this->facebook = $facebook;

        return $this;
    }

    public function getInstagram(): ?string
    {
        return $this->instagram;
    }

    public function setInstagram(?string $instagram): self
    {
        $this->instagram = $instagram;

        return $this;
    }

    public function getTwitter(): ?string
    {
        return $this->twitter;
    }

    public function setTwitter(?string $twitter): self
    {
        $this->twitter = $twitter;

        return $this;
    }

    public function getYoutube(): ?string
    {
        return $this->youtube;
    }

    public function setYoutube(?string $youtube): self
    {
        $this->youtube = $youtube;

        return $this;
    }

    public function getDeezer(): ?string
    {
        return $this->deezer;
    }

    public function setDeezer(?string $deezer): self
    {
        $this->deezer = $deezer;

        return $this;
    }

    public function getSpotify(): ?string
    {
        return $this->spotify;
    }

    public function setSpotify(?string $spotify): self
    {
        $this->spotify = $spotify;

        return $this;
    }

    public function getSoundcloud(): ?string
    {
        return $this->soundcloud;
    }

    public function setSoundcloud(?string $soundcloud): self
    {
        $this->soundcloud = $soundcloud;

        return $this;
    }

    public function getUser(): ?Users
    {
        return $this->user;
    }

    public function setUser(?Users $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(string $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    public function getSubgenre(): ?string
    {
        return $this->subgenre;
    }

    public function setSubgenre(string $subgenre): self
    {
        $this->subgenre = $subgenre;

        return $this;
    }

}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Release;
use App\Entity\Live;

class HomeController extends AbstractController
{
    public function home()
    {
        return $this->render('home/home.html.twig', [
            'controller_name' => 'HomeController',
        ]);
    }
    /**
     * matthieu : efface l'article ciblé (id_release)
     */
    public function showAll()
    {
        $entityManager = $this->getDoctrine()->getManager();
        $all_releases = $entityManager->getRepository(Release::class)->findAll();

        $entityManager = $this->getDoctrine()->getManager();
        $all_lives = $entityManager->getRepository(Live::class)->findAll();
        return $this->render('home/actualite.html.twig', [
            'releases' => $all_releases,
            'lives' => $all_lives,
        ]);
    }
    public function listepromo()
    {
        return $this->render('home/listepromo.html.twig', [
            'controller_name' => 'HomeController',
        ]);
    }
    public function mentionslegales()
    {
        return $this->render('home/mentionslegales.html.twig', [
            'controller_name' => 'HomeController',
        ]);
    }
    public function tutoriel()
    {
        return $this->render('home/tutoriel.html.twig', [
            'controller_name' => 'HomeController',
        ]);
    }
}

templates/home/actualite.html.twig
{% extends 'base.html.twig' %}

{% block title %}Machinazic - Actualités{% endblock %}

{% block body %}
    <main class="container"> 
        <div class="m-3">
            <h1 class="titre_home my-4 py-3 text-uppercase text-center">Les actualités de Machinazic</h1>
            <p> Retrouvez ici les dernières sorties et évènements qui ont bénéficié des services de Machinazic pour leur promo</p>
        </div>

        <div class="row mx-3 my-4">
            <h2 class="py-2 last col-xl-12 col-sd-12 text-center">Les Dernières Sorties</h2>
            {% for release in releases %}
                <div class="col-xl-4 col-sm-12">
                    <a href="{{ path('release', {release_id: release.id}) }}"><img id="image_article" src="{{asset('assets/img/uploads/' ~ release.image) }}" alt="image associée à l'article" class="img-thumbnail mx-auto rounded d-block"></a>
                </div>
                <div class="col-xl-8 col-sm-12 my-auto">
                    <p> <i class="fas fa-music">&nbsp;</i> Retrouvez <span class="font-weight-bold">{{release.artist}}</span> qui présente <span class="font-italic">{{release.releaseName}} !</span></p>
                    <p class="text-right pr-5">&nbsp;<i class="fas fa-compact-disc"></i> Sortie ({{release.releaseType}}) le {{release.dateRelease}} <a href="{{ path('release', {release_id: release.id}) }}"><i class="pl-2 fas fa-external-link-alt"></i></a></p>
                </div>
            {% endfor %}
        </div>

        <div class="row mx-3 my-4">
        <h2 class="py-2 last col-xl-12 col-sd-12 text-center">Les Derniers Évènements</h2>
            {% for live in lives %}
                <div class="col-xl-4 col-sm-12">
                    <a href="{{ path('live', {live_id: live.id}) }}"><img id="image_article" src="{{asset('assets/img/uploads/' ~ live.image) }}" alt="image associée à l'article" class="img-thumbnail mx-auto rounded d-block"></a>
                </div>
                <div class="col-xl-8 col-sm-12 my-auto">
                    <p> <i class="fas fa-music">&nbsp;</i> Retrouvez <span class="font-weight-bold">{{live.artist}}</span> qui présente <span class="font-italic">{{live.liveName}} !</span></p>
                    <p class="text-right pr-5">&nbsp;<i class="fas fa-compact-disc"></i> Retrouvez en {{live.liveType}} le {{live.dateLive}} <a href="{{ path('live', {live_id: live.id}) }}"><i class="pl-2 fas fa-external-link-alt"></i></a></p>
                </div>
            {% endfor %}
        </div>
    </main>

{% endblock %}



 {# <main class="container">
     <section class="pt-4 bg-grey px-3">

        <div class="pt-4 text-center">
            <h1>Actualités</h1>
            </div>
            <div class="row pt-4">
                <div class="col-12 col-xl-12 text-center">
                    <h4>Machinazic présente : LEFA en concert</h4>
            </div>
        
                <div class="pt-4 col-12 col-xl-4">
                    <img src="{{ asset('assets/img/lefa.webp') }}" alt="" class="img-thumbnail">
                </div>
                <div class="col-12 col-xl-8 text-center align-self-center">
                    <p> Etiquette genre Bar-Discothèque Le Fragonard (Grenoble)</p>
                    <p>Artiste : Jean Guy Balnave Genre : Hard Musette </p>
                    <p>  Date : 32/07/2020 à 20h12</p>
                </div>
                <div class="pt-4 col-12 col-xl-12 text-center">
                <p> Description : Suite à la sortie de son album « Rupture de stock », unanimement spolié par la critique et
                        atteignant déjà plus de 27 ventes (streaming inclus), Jean-Guy Balnave viendra défendre cet opus
                        le 32 juillet sur la scène du bar-discothèque Le Fragonard à Grenoble. Farouchement engagé, cet artiste
                        atypique et mal rasé nous fera découvrir son univers, oscillant en permanence entre poésies légères et
                        pathologies graves non prises en charge. Jean-Guy nous fera également l'honneur de présenter quelques
                        titres inédits, dont le surprenant « Je ne suis pas celle que vous croivez » dans lequel il incarne une brosse
                        à dents de couleur pourpre. Energie, bonne humeur et effluves corporelles diverses vous attendent donc
                        dès 20h12 ce soir là sur la scène du Fragonard pour un moment qui s'annonce d'ores et déjà mémorable</p>
                </div>
                <div class="pt-4 col-12 col-xl-12 text-center">
                    <p class="justify-content-center"></p>
                    <p>Hashtags : #rupturedestock #balnave #live #grenoble #hardmusette
                        #show #concert #textes #lefragonard #billets #blablabla #weshmagueule</p>
                </div>
                <div class="pt-4 col-12 col-xl-6 text-center">
                    <p class="justify-content-center"></p>
                    <p>Vidéo Youtube <a href="#"><i class="fa fa-youtube"></i></a></p>
                </div>
                <div class="pt-4 col-12 col-xl-6 text-center">
                    <p class="justify-content-center"></p>
                    <p>Lecteur type soundcloud<i class="fa fa-soundcloud"></i>, spotify<i class="fa fa-spotify"></i>....<a href="#"></a></p>
                </div>
            </div>
        </section>
    </main> #}

templates/home/home.html.twig
{% extends 'base.html.twig' %}

{% block title %}Machinazic - bienvenue
{% endblock %} 

{% block body %}
{# <div class="text-center">
<img class="img-fluid text-center" src="{{ asset('assets/img/banniere.png') }}" id="banniere">
</div> #}
	<main class="container">
		<div class="text-center">		
			<h1 class="titre_home my-4 mx-n3">MACHINAZIC<sup>&copy;</sup> - Accélérateur De Promo Online</h1>
		</div>
			<div class="row justify-content-center">
				<div class="col-12 col-xl-6 align-self-center">
					<div id="presentation" class="d-flex flex-column justify-content-center">
						<p class="font-italic pb-2 text-justify lead"><i class="fas fa-quote-left mr-2 mt-2"></i>"Vous êtes un artiste sur le point de sortir un projet discographique ou de faire un concert ? Vous souhaitez utiliser les réseaux sociaux sans devoir passer des heures sur votre promo? Vous aimeriez partager une page d'informations personnalisée mais vous ne savez pas comment vous y prendre ?"</p>
						<div class="border-top w-50 align-self-center"></div>
						<p class="text-justify lead pt-2">Machinazic<sup>&copy;</sup> est la solution qu'il vous faut ! Laissez-vous guider par notre formulaire automatisé et générez rapidement votre page de promo, à partager ensuite sur tous vos réseaux sociaux ou vos listes de diffusion.</p>
					</div>
				</div>
				<div id="carouselExampleCaptions" class="carousel slide col-12 col-xl-6" data-ride="carousel">
					<ol class="carousel-indicators">
						<li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
						<li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
						<li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
					</ol>
					<div class="carousel-inner">
						<div class="carousel-item active">
							<img src="{{ asset('assets/img/slide1.jpg') }}" class="d-block w-100" alt="Slide Accueil 1">
							<div class="carousel-caption d-md-block">
								<h5>Comment gérer ma promo en ligne?</h5>
								<p class="font-italic">"Mon groupe et moi voulons une page de promo en ligne mais on n'y connait rien..."</p>
							</div>
						</div>
						<div class="carousel-item">
							<img src="{{ asset('assets/img/slide7.jpg') }}" class="d-block w-100" alt="Slide Accueil 2">
							<div class="carousel-caption d-md-block">
								<h5>Machinazic&copy; : obtenez votre page de promo en quelques clics !</h5>
								<p class="font-italic">"Je remplis le formulaire et j'obtiens une page prête à être diffusée pour faire ma promo."</p>
							</div>
						</div>
						<div class="carousel-item">
							<img src="{{ asset('assets/img/slide8.jpg') }}" class="d-block w-100" alt="Slide Accueil 3">
							<div class="carousel-caption d-md-block">
								<h5>Idéal pour promouvoir un concert, une sortie discographique, etc...</h5>
								<p class="font-italic">"Grâce aux 2 formulaires dédiés, concert ou sortie discographique, je peux cibler plus précisément ma promo!"</p>
							</div>
						</div>
					</div>
					<a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
						<span class="carousel-control-prev-icon" aria-hidden="true"></span>
						<span class="sr-only">Previous</span>
					</a>
					<a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
						<span class="carousel-control-next-icon" aria-hidden="true"></span>
						<span class="sr-only">Next</span>
					</a>
				</div>
				<div class="col-12 col-xl-12 text-center ">
					<h2 class="titre_home mt-4 mx-n3">COMMENT CA MARCHE ?
					</h2>
					<div class="row">
						<div class="col-sd-12 col-xl-12">
							<p id="vous_inscrire" class="font-italic  text-right">Vous devez vous <a href="{{ path('subscription_addUser') }}">inscrire</a> pour pouvoir utiliser nos services.</p>
							<p>Nous vous proposons deux types de promos : une pour vos créations musicales et une pour vos concerts.</p>
						</div>
						<div class="col-sd-12 col-xl-6">
							<a href="{{ path('live_addLive') }}">
								<img class="imagepromo" src="{{ asset('assets/img/live.jpg') }}" alt="">
								<p class="imagepromo-legende">Pour un concert, un festival...</p>
							</a>
						</div>
						<div class="col-sd-12 col-xl-6">
							<a href="{{ path('release_addRelease') }}">
								<img id="miror" class="imagepromo" src="{{ asset('assets/img/release3.jpg') }}" alt="">
								<p class="imagepromo-legende">Pour la sortie d'un album, d'un single...</p>
							</a>
						</div>
					</div>
				</div>
		</main>
	{% endblock %}

	{% block js %}
	<script>alert("Gestion des cookies, acceptez-vous?")
	{% endblock %}