src/Entity/Genre.php
<?php

namespace App\Entity;

use App\Repository\GenreRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=GenreRepository::class)
 */
class Genre
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $genre_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $subgenre_name;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getGenreName(): ?string
    {
        return $this->genre_name;
    }

    public function setGenreName(string $genre_name): self
    {
        $this->genre_name = $genre_name;

        return $this;
    }

    public function getSubgenreName(): ?string
    {
        return $this->subgenre_name;
    }

    public function setSubgenreName(string $subgenre_name): self
    {
        $this->subgenre_name = $subgenre_name;

        return $this;
    }
}

src/Entity/Release.php
<?php

namespace App\Entity;

use App\Repository\ReleaseRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\EntityManagerInterface;

/**
 * @ORM\Entity(repositoryClass=ReleaseRepository::class)
 * @ORM\Table(name="`release`")
 */
class Release
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $artist;

    /**
     * @ORM\Column(type="datetime", length=255)
     */
    private $date_created;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $release_type;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $date_release;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $release_name;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $facebook;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $instagram;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $twitter;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $youtube;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $deezer;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $spotify;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $soundcloud;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="releases")
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $genre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $subgenre;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getArtist(): ?string
    {
        return $this->artist;
    }

    public function setArtist(string $artist): self
    {
        $this->artist = $artist;

        return $this;
    }

    public function getDateCreated(): ?\DateTimeInterface
    {
        return $this->date_created;
    }

    public function setDateCreated(\DateTimeInterface $date_created): self
    {
        $this->date_created = $date_created;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getReleaseType(): ?string
    {
        return $this->release_type;
    }

    public function setReleaseType(string $release_type): self
    {
        $this->release_type = $release_type;

        return $this;
    }

    public function getDateRelease(): ?string
    {
        return $this->date_release;
    }

    public function setDateRelease(string $date_release): self
    {
        $this->date_release = $date_release;

        return $this;
    }

    public function getReleaseName(): ?string
    {
        return $this->release_name;
    }

    public function setReleaseName(string $release_name): self
    {
        $this->release_name = $release_name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getFacebook(): ?string
    {
        return $this->facebook;
    }

    public function setFacebook(?string $facebook): self
    {
        $this->facebook = $facebook;

        return $this;
    }

    public function getInstagram(): ?string
    {
        return $this->instagram;
    }

    public function setInstagram(?string $instagram): self
    {
        $this->instagram = $instagram;

        return $this;
    }

    public function getTwitter(): ?string
    {
        return $this->twitter;
    }

    public function setTwitter(?string $twitter): self
    {
        $this->twitter = $twitter;

        return $this;
    }

    public function getYoutube(): ?string
    {
        return $this->youtube;
    }

    public function setYoutube(?string $youtube): self
    {
        $this->youtube = $youtube;

        return $this;
    }

    public function getDeezer(): ?string
    {
        return $this->deezer;
    }

    public function setDeezer(?string $deezer): self
    {
        $this->deezer = $deezer;

        return $this;
    }

    public function getSpotify(): ?string
    {
        return $this->spotify;
    }

    public function setSpotify(?string $spotify): self
    {
        $this->spotify = $spotify;

        return $this;
    }

    public function getSoundcloud(): ?string
    {
        return $this->soundcloud;
    }

    public function setSoundcloud(?string $soundcloud): self
    {
        $this->soundcloud = $soundcloud;

        return $this;
    }

    public function getUser(): ?Users
    {
        return $this->user;
    }

    public function setUser(?Users $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(string $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    public function getSubgenre(): ?string
    {
        return $this->subgenre;
    }

    public function setSubgenre(string $subgenre): self
    {
        $this->subgenre = $subgenre;

        return $this;
    }

}

src/Controller/ReleaseController.php
<?php

namespace App\Controller;

use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Release;
use App\Entity\Genre;
use Symfony\Component\HttpFoundation\Request;
use Intervention\Image\ImageManager as image;


class ReleaseController extends AbstractController
{
    public function release()
    {
        return $this->render('release/release.html.twig', [
            'controller_name' => 'ReleaseController',
        ]);
    }

    /**
     * Permet d'ajouter une release en base de données (par rapport à l'id d'un user donc l'user doit être connecté)
     */
    public function addRelease(MailerInterface $mailer)
    {
        //matthieu VERIFIER SI UN USER EST CONNECTÉ AVANT DE POUVOIR LANCER LA PAGE
        if (!$this->getUser()) {
            $this->addFlash('danger', 'Seul les utilisateurs connectés peuvent créer une sortie.');
            return $this->redirectToRoute('app_login'); // redirection vers la liste des recettes
        }

        //Matthieu : LISTE DES GENRES
        $genres = $this->getDoctrine()->getRepository(Genre::class)->findAllGenre();
        $genre_list = [];
        foreach ($genres as $sub) {
            $genre_list[] = $sub->getGenreName();
        }

        // LISTE DES SOUS GENRES axel On aurait également pu faire un find($id_sub) lors de la soumission, on fait une comparaison via un tableau là
        $subgenres = $this->getDoctrine()->getRepository(Genre::class)->findAllSubGenre();
        $list_available_sub = [];
        foreach ($subgenres as $sub) {
            // axel : tableau contenant tous les id des subgenres (tous, sans exception)
            $list_available_sub[] = $sub->getId();
        }

        //Matthieu : LISTE RELEASE_TYPE
        $release_type = ['CD', 'Digital', 'Vinyl', 'Cassette'];

        if (!empty($_POST)) {
            $safe = array_map('trim', array_map('strip_tags', $_POST));
            $now = new \DateTime('now');
            $now->format('Y-m-d');
            $postdate = new \Datetime($safe['release_date']);
            $postdate->format('Y-m-d');

            $errors = [
                //anthony Verif Artiste
                (strlen($safe['artist']) < 2 || strlen($safe['artist']) > 100) ? 'Le nom de l\'artiste doit comporter entre 2 et 100 caractères' : null,

                //matthieu Verif genre, menu select
                (!in_array(($safe['genre']), $genre_list)) ? 'Veuillez indiquer un genre comme indiqué dans la liste' : null,

                // axel: Verif subgenre, je force via un ternaire la valeur "0" puisque sur le <select> j'ai mis un disabled
                // via ce ?? 0 si subgenre n'est pas choisi, il vaudra 0 dans cette condition, 0 ne peut pas être un id en SQL
                (!in_array(($safe['subgenre'] ?? 0), $list_available_sub)) ? 'Veuillez indiquer un sous-genre comme indiqué dans la liste' : null,

                //anthony Verif Nom De La Sortie
                (strlen($safe['release_name']) < 1 || strlen($safe['release_name']) > 100) ? 'Le nom de la sortie doit comporter entre 1 et 100 caractères' : null,

                //matthieu Verif date (ne peut pas être plus tôt que now())
                (empty($postdate) || $now > $postdate) ? "Votre release ne peut être publiée à une date antérieure à celle d'aujourd'hui" : null,

                //Matthieu Verif CD CASSETTE VINYL DIGITAL
                (!in_array(($safe['release_type']), $release_type)) ? 'Veuillez indiquer un type de sortie' : null,

                //anthony Verif Description
                (strlen($safe['description']) < 50 || strlen($safe['description']) > 1500) ? 'La description doit comporter entre 50 et 1500 caractères' : null,

                //anthony Verif Facebook
                (strlen($safe['fb']) > 200) ? 'L\'URL ne doit pas comporter plus de 200 caractères' : null,

                //anthony Verif Instagram
                (strlen($safe['ig']) > 100) ? 'L\'URL ne doit pas comporter plus de 100 caractères' : null,

                //anthony Verif Twitter
                (strlen($safe['twitter']) > 100) ? 'L\'URL ne doit pas comporter plus de 100 caractères' : null,

                //anthony Verif Youtube
                (strlen($safe['yt']) > 50) ? 'L\'URL ne doit pas comporter plus de 50 caractères' : null,

                //anthony Verif Deezer
                (strlen($safe['deezer']) > 30) ? 'L\'URL ne doit pas comporter plus de 30 caractères' : null,

                //anthony Verif Spotify
                (strlen($safe['spotify']) > 40) ? 'L\'URL ne doit pas comporter plus de 40 caractères' : null,

                //anthony Verif Soundcloud
                (strlen($safe['soundcloud']) > 100) ? 'L\'URL ne doit pas comporter plus de 100 caractères' : null
            ];

            //axel Automatiquement supprimer les entrées vides de mon tableau
            $errors = array_filter($errors);

            //gestion des images         
            $image_name = null;
            if (isset($_FILES) && !empty($_FILES)) {
                $extension = pathinfo($_FILES['image']['name'], PATHINFO_EXTENSION);
                $image_name = $safe['artist'];
                $image_final_name = $image_name . '.' . $extension;
            dump($image_final_name);
                //$image_bdd_name = ;
                $this->uploadImage($image_name, 'uploads', 80, ['image/jpeg', 'image/jpg', 'image/pjpeg', 'image/png'], 1);                           
            }


            if (count($errors) === 0) {    
                

                //Gestion du subgenre
                $subgenre = $this->getDoctrine()->getRepository(Genre::class)->findOneBy(['id' => $safe['subgenre']]);

                //matthieu new Entity
                $release = new Release();
                $release->setArtist($safe['artist']);
                $release->setDateCreated($now);
                $release->setImage($image_final_name);
                $release->setReleaseName($safe['release_name']);
                $release->setGenre($safe['genre']);
                $release->setSubgenre($subgenre->getSubgenreName());
                $release->setReleaseType($safe['release_type']);
                $release->setDateRelease($safe['release_date']);
                $release->setDescription($safe['description']);
                $release->setUser($this->getUser());



                //matthieu Input qui ne sont pas obligatoire
                //matthieu SOCIAL
                if (!empty($safe['fb'])) {
                    $release->setFacebook($safe['fb']);
                }
                if (!empty($safe['ig'])) {
                    $release->setInstagram($safe['ig']);
                }
                if (!empty($safe['twitter'])) {
                    $release->setTwitter($safe['ig']);
                }
                //matthieu MUSIC
                if (!empty($safe['yt'])) {
                    $release->setYoutube($safe['yt']);
                }

                if (!empty($safe['deezer'])) {
                    $release->setDeezer($safe['deezer']);
                }

                if (!empty($safe['soundcloud'])) {
                    $release->setSoundcloud($safe['soundcloud']);
                }

                if (!empty($safe['spotify'])) {
                    $release->setSpotify($safe['spotify']);
                }

                //matthieuEnregistrement des données si les données sont SET
                //matthieu$release->setImage($safe['image'])

                // Insertion des données SQL
                $entityManager = $this->getDoctrine()->getManager(); // C'est un peu comme la connexion bdd
                $entityManager->persist($release); // Execution de la requete
                $entityManager->flush(); // Déconnexion

                $this->addFlash('success', 'Votre article "sortie" a bien été ajouté');
                return $this->redirectToRoute('user');

            } else {
                //matthieu Il y a des erreurs
                $errorsMessage = implode('<br>', $errors); // implode() transforme mon tableau d'erreur en une chaine de caractères
                $this->addFlash('danger', $errorsMessage);
            }
        }

        return $this->render('release/addRelease.html.twig', [
            'input_saisis' => $safe ?? [], // Me permet de reprendre mes données déjà saisies dans la vue
            'genres' => $genres,
        ]);
    }


    /**
     * matthieu : affiche un article_release (en fonction de son ID)
     */
    public function viewRelease($release_id)
    {
        //matthieu On accède au manager (connexion DB)
        $entityManager = $this->getDoctrine()->getManager();
        //matthieu On passe le paramètre $release_id récupéré de l'URL pour chercher la recette donnée
        $release = $entityManager->getRepository(Release::class)->find($release_id);

        if (!$release) {
            throw $this->createNotFoundException('Cette article n\'existe pas');
        }

        return $this->render('release/release.html.twig', [
            'release' => $release
        ]);
    }

    /**
     * matthieu : efface l'article ciblé (id_release)
     */
    public function deleteRelease(int $release_id)
    {

        // On accède au manager (connexion DB)
        $entityManager = $this->getDoctrine()->getManager();
        // On passe le paramètre $id_cook récupéré de l'URL pour chercher la recette donnée
        $release = $entityManager->getRepository(Release::class)->find($release_id);

        if (!$release) {
            throw $this->createNotFoundException('Cette recette n\'existe pas');
        }

        if (!empty($_POST)) {
            if (isset($_POST['action']) && $_POST['action'] === 'delete') {
                // Suppression
                $entityManager->remove($release);

templates/release/deleteRelease.html.twig
{% extends 'base.html.twig' %}

{% block title %}Suppression de la sortie{{release.id}}{% endblock %}

{% block body %}
    <main class="container-fluid" id="delete">
    {% for label, messages in app.flashes %}
        <div class="alert text-center alert-{{ label }}">
            {% for message in messages %}
                {{ message|raw }}
            {% endfor %}
        </div>
    {% endfor %}
        <div class="row text-center justify-content-center">
            <div id="login_zone" class="col-12 col-xl-4 justify-content-center px-5 pb-5 pt-2 mt-5">
                <a href="{{ path('home') }}" class="d-inline-block">
                    <img src="{{ asset('assets/img/machinazic-logo.png') }}" alt="">
                </a>
                <h1>Suppression d'un article <span class="text-italic">"sortie"</span></h1>
                <p class="delete_p">Article posté le <span class="font-weight-bold">{{release.dateCreated|date("d/m/Y")}}</span> - <span class="font-weight-bold">{{release.releaseName}}</span></p>
                <form method="post">
                    <a href="{{ path('user') }}">Annuler</a>
                    <input type="hidden" name="action" value="delete">
                    <button class="btn btn-rouge" type="submit">Oui, je veux supprimer cet article</button>                        
                </form>
            </div>
        </div>
    </main>

{% endblock %}

templates/release/release.html.twig
{% extends 'base.html.twig' %}

{% block title %}Machinazik - sortie {{release.id}}
{% endblock %}

{% block body %}
	<main class="container">
		<div class="row justify-content-center">
			<div class="col-12 text-center">
				<h1 class="titre_article">Machinazic présente :</h1>
				<h2 id="who">
					<span class="font-italic">{{release.releaseName}}</span>, la nouveauté de
					<span class="font-weight-bold">{{ release.artist }}</span>
				</h2>
			</div>
            <div class="col-xl-6"><img id="image_article" src="{{asset('assets/img/uploads/' ~ release.image) }}" alt="image associée à l'article" class="img-thumbnail rounded mx-auto d-block"></div>

                <div class="col-xl-3 text-center align-self-center">
                <div id="summary">
					<p>
						<span class="font-weight-bold"> Genre : </span>
						{{ release.genre }}</p>
					<p>
						<span class="font-weight-bold">Sous-genre : </span>
						{{ release.subgenre }}
					</p>
					<p>
						<span class="font-weight-bold">Sortie le  : </span>
						{{ release.dateRelease }}
					</p>
					<p>
						<span class="font-weight-bold">Format : </span>
						{{ release.releaseType }}
					</p>
                    </div>
				</div>
			<div class="col-12 col-xl-12 text-center mt-5">
				<p class="justify-content-center"></p>
				<p class="mb-4"><span  id="apropos">Découvrez <i class="fas fa-headphones-alt"></i>&nbsp;"{{release.artist}}"&nbsp;<i class="fas fa-headphones-alt"></i></span></p>
				<p class="m-3 text-justify">
										{{ release.description }}
				</p>
				<div id="keywords">
					<p class="font-weight-bold"><i class="fas fa-hashtag"></i> Mots-clefs :</p>
					<p>#Machinazic #Musique #Music #Musicpromo #New #Nouveau #Out #Release #{{release.releaseType}} #{{release.genre}} #{{release.subgenre}} #{{release.artist}} #Promo </p>
				</div>

				{# API #}
				<div class="col-12 col-xl-12 text-center mt-5 no-view-mobile">
					{% if release.youtube is not null %}
						<iframe class="m-2" width="560" height="315" src="https://www.youtube.com/embed/{{release.youtube}}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
					{% endif %}	
					{% if release.spotify is not null %}
						<iframe class="m-2" src="https://open.spotify.com/embed/artist/{{release.spotify}}" width="650" height="380" frameborder="0" allowtransparency="true"></iframe>
					{% endif %}	
				</div>


				{# SOCIAL #}
				<div class="d-flex flex-row justify-content-center">
					{% if release.facebook is not null %}
						<div class="p-4">
							<a href="https://www.facebook.com/{{release.facebook}}">
								<img class="logo" src="{{ asset('assets/img/logos/facebook2.png') }}" alt="">
							</a>
						</div>
					{% endif %}

					{% if release.instagram is not null %}
						<div class="p-4">
							<a href="https://www.instagram.com/{{release.instagram}}">
								<img class="logo" src="{{ asset('assets/img/logos/instagram.png') }}" alt="">
							</a>
						</div>
					{% endif %}

					{% if release.twitter is not null %}
						<div class="p-4">
							<a href="https://www.twitter.com/{{release.twitter}}">
								<img class="logo" src="{{ asset('assets/img/logos/twitter2.png') }}" alt="">
							</a>
						</div>
					{% endif %}
				</div>

				{# MUSIQUE #}
				<div class="d-flex flex-row justify-content-center">
					
					{% if release.youtube is not null %}
						<div class="p-4">
							<a href="https://www.youtube.com/watch?v={{release.youtube}}">
								<img class="logo" src="{{ asset('assets/img/logos/youtube1.png') }}" alt="">
							</a>
						</div>
					{% endif %}	

					{% if release.soundcloud is not null %}
						<div class="p-4">
							<a href="https://www.soundcloud.com/{{release.soundcloud}}">
								<img class="logo" src="{{ asset('assets/img/logos/soundcloud2.png') }}" alt="">
							</a>
						</div>
					{% endif %}	
				</div>
				<div class="d-flex flex-row justify-content-center">
					{% if release.deezer is not null %}
						<div class="p-4">
							<a href="https://www.deezer.com/fr/{{release.deezer}}">
								<img class="logo" src="{{ asset('assets/img/logos/deezer2.png') }}" alt="">
							</a>
						</div>
					{% endif %}

					{% if release.spotify is not null %}
						<div class="p-4">
							<a href="https://www.spotify.com/{{release.spotify}}">
								<img class="logo" src="{{ asset('assets/img/logos/spotify2.png') }}" alt="">
							</a>
						</div>
					{% endif %}			
				</div>
				<div id="share">
						<a href="https://www.facebook.com/share.php?u=https://www.discogs.com/"><i class="fab fa-facebook-square"></i>&nbsp;Partager sur Facebook</a>
					</div>	
			</div>
		</div>

		<div class="d-flex justify-content-end" >
			<p class="font-italic mt-3 pr-4">Article crée le
				{{ release.dateCreated|date("m/d/Y") }}</p>
		</div>

	</main>
{% endblock %}